kumuluzee:
  name: product-detail-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ProductDetailDS
      connection-url: jdbc:postgresql://localhost:5432/product-details
      username: dbuser
      password: postgres
      pool:
        max-size: 1
